import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sale Report",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}


// useSessionGuard.js
import { useEffect } from "react";
import { useRouter } from "next/navigation";

export default function useSessionGuard() {
  const router = useRouter();

  useEffect(() => {
    const sessionId = localStorage.getItem("sessionId");
    const email = localStorage.getItem("email");
    if (!sessionId || !email) {
      router.replace("/admin");
      return;
    }
    fetch("/api/admin/validate-session", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ email, sessionId }),
    }).then(async res => {
      if (!res.ok) {
        localStorage.clear();
        router.replace("/admin");
      }
    });
  }, []);
}
